### ISSUE TITLE
.npmignore

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db-store#113]
Things like `.nyc_output` and the `test` folder can be added to .npmignore to reduce the package size.
 
![image](https://user-images.githubusercontent.com/106148/130074230-d9053bff-ab5c-45fd-bfda-b64f7ac01a85.png)

**Comment by aphelionz** [comment]
@julienmalard ^

**Comment by julienmalard** [comment]
Just to check before I add them: should orbitdb/identity/**, .github/** and/or LICENCE and README be excluded as well?

**Comment by aphelionz** [comment]
* LICENSE and README - keep
* orbitdb/ folder - drop
* .github - drop
* .nyc_output - drop

**Comment by aphelionz** [comment]
Thank you!

**Comment by aphelionz** [comment]
Great work!

**Comment by julienmalard** [comment]
Thanks @aphelionz !
