### ISSUE TITLE
Allow updateIndex to be async

### ISSUE THREAD

**Issue by fazo96** [orbitdb/orbit-db-store#18]
Hello @haadcode, I love orbit-db!

I am implementing a custom store for a specific application, but the index-building operation (`updateIndex`) involves some external I/O. I know this makes the index not deterministic, but it should not be an issue for my use case, at least for now.

At [this line](https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L108) the `updateIndex` call is made, but the call does not use `await` (even though the caller is async) so if `updateIndex` returns a promise it would be executed concurrently and the `replicated` event would get emitted while the index isn't ready yet.

I'd be happy to submit a PR, just wanted to know if I'm missing something important

**Comment by haadcode** [comment]
Hi @fazo96! So happy to hear that OrbitDB is working for you! ❤️😄 

Your idea to make `updateIndex` calls async sounds good! I don't see why we couldn't implement it as you propose. 

Perhaps in addition to changing it internally in Store, we should also add `async` to the base class in https://github.com/orbitdb/orbit-db-store/blob/master/src/Index.js#L50 to make the intention of the public API clear. 

Note also that `updateIndex()` gets called in multiple places inside Store: https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L416, https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L399, https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L202. It might make sense to create an internal `async _updateIndex()` function that calls the index as it does now and then on those ^ lines call `this._updateIndex()` function. This would make it a tad cleaner and easier to find what does what. What do you think?

Would be happy to review the PR and merge it in! If you do, make sure to run the tests in OrbitDB with the PR (`npm link orbit-db-store && npm test`) to make sure nothing breaks.

**Comment by haadcode** [comment]
Did some clean up today, line numbers may not match anymore.

**Comment by haadcode** [comment]
This was implemented in https://github.com/orbitdb/orbit-db-store/commit/9029c0f6968859366d9e2d5ca681608f1782cfa6 and merged to master. Will appear in the next release.

**Comment by fazo96** [comment]
Wow thanks, looking forward to it! 👍
