### ISSUE TITLE
This function doesn't match the API

### ISSUE THREAD

**Issue by willemneal** [orbitdb/orbit-db-store#26]
https://github.com/orbitdb/orbit-db-store/blob/931c452e5197bcd4a2cb716eecfe675da87e2838/src/Store.js#L305

```js 
loadFromSnapshot(hash, onProgressCallback)
```
Load the state of the database from a snapshot. hash is the IPFS Multihash of the snapshot data. Returns a Promise that resolves when the database has been loaded.

**Comment by haadcode** [comment]
@willemneal thanks for reporting this! And sorry for the delay.

Would you care to create a PR that updates the documentation?
